### ISSUE TITLE
Issues with clustering a t-SNE

### ISSUE THREAD

**Issue by fmaguire** [PoonLab/covizu#145]
Hi,

Thanks for all the work on this tool, I was just trying to deploy it on some data and noticed: https://github.com/PoonLab/covizu/blob/3c03c19546ee9b273045d411959715a51519bf96/scripts/hclust.R#L27

You might have tried something like this during development but given that t-SNEs don't really preserve distances at all or densities well [1](https://lvdmaaten.github.io/tsne/), its not really ideal to cluster the results of a t-SNE as you can end up with visually appealing but nonsensical clusters [2](https://link.springer.com/chapter/10.1007%2F978-3-319-68474-1_13). 

If the dimensionality is too high to cluster quickly/effectively, a classic dimensionality reduction method like LDA or even PCA might be a better option.

**Comment by ArtPoon** [comment]
Hi @fmaguire - thanks for the feedback!  Yes, I have explored PCA during development, and I have read the caveats in the literature and online on using t-SNE.  In fact we are abandoning this approach altogether in refactoring the backend (see `dev` branch).  Since we're pretty close to pushing the new pipeline into production, I am going to close this issue.

**Comment by fmaguire** [comment]
Ah nice, totally missed the dev branch. I'll take a look now, cheers!
