### ISSUE TITLE
Use a different highlighting scheme for selected and active beads

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#147]
When iterating through search results, the highlighting of selected beads vanishes as the user iterates through the results.  We should have one set of highlights persisting during an active search, and a different highlighting scheme for the current bead selection.

**Comment by ArtPoon** [comment]
Bring selected bead into foreground of beadplot

**Comment by RouxCil** [comment]
If I remove the outer grey circle around the selection I feel like I am playing where's Wally (see the comparison below).

<p float="left">
  <img alt="Screen Shot 2020-10-19 at 13 16 58" src="https://user-images.githubusercontent.com/6604824/96489533-8dee1f80-120d-11eb-9507-d6402fbe489f.png" width="350">
<img alt="Screen Shot 2020-10-19 at 13 16 21" src="https://user-images.githubusercontent.com/6604824/96489526-8cbcf280-120d-11eb-9ec7-35886293e53b.png" width="350">
</p>

Because of this I am going to change the colour of the outer circle to a different colour when the iteration with the next button starts and not remove it completely.

**Comment by RouxCil** [comment]
- [ ] What index should be shown when a cluster is clicked?
- [ ] What cluster should be selected when the search is run?
- [ ] The "info tables" should be updated to the selected bead when the next button/previous buttons are used
- [ ] Different highlighting scheme for the current bead
- [ ] Bring selected bead into foreground of beadplot

**Comment by ArtPoon** [comment]
* When a cluster is clicked that contains search results, the index should be that of the first hit in that cluster.
* Right hand side (information panel) should display the results of the corresponding bead in the cluster.

**Comment by ArtPoon** [comment]
We have to handle the edge case where the user clicks on an unselected cluster that precedes the first cluster with matching points.  Clicking "next" should both switch to this first cluster and should not increment the counter (which would already display 1).

**Comment by ArtPoon** [comment]
Second edge case, the opposite situation where the user has navigated to an unselected cluster and hits "previous" to jump to the preceding cluster with matches.

**Comment by ArtPoon** [comment]
I'd prefer to use the halo when user clicks on a bead, rather than drop everything else in the beadplot into transparency - this would be more consistent with the interface we have for the time-scaled tree.

**Comment by RouxCil** [comment]
New separate issues have been populated with the information in this issue
