### ISSUE TITLE
Search is still broken with TypeError

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#167]
```js
beadplot.js:383 Uncaught TypeError: Cannot read property 'variants' of undefined
    at beadplot (beadplot.js:383)
    at select_beads_by_comparators (search.js:72)
    at select_beads_by_substring (search.js:120)
    at search (search.js:247)
    at HTMLInputElement.<anonymous> ((index):234)
    at HTMLInputElement.dispatch (jquery.js:5429)
    at HTMLInputElement.elemData.handle (jquery.js:5233)
```

**Comment by ewong347** [comment]
Possible fix with d326afc 
Line 62:70 in search.js 

```javascript
select_beads_by_comparators(clusters, points){
       (....)
	if (d3.selectAll('.clicked').empty()){

	  var first_cluster_idx;
	  d3.select(rects.nodes().pop()).attr("class", "clicked");
	  d3.select(rects.nodes().pop()).each(function(d) {
 	        first_cluster_idx = d.cluster_idx;
  	        create_clusterH(d, this);
	  });
	  beadplot(first_cluster_idx);
```
```first_cluster_idx``` is undefined, which passes the undefined object to downstream processes. Adding this line will set a random beatplot cluster id in range(0,238) if ```first_cluster_idx``` isn't defined. ```rect.nodes.pop()``` is the issue here I believe, I'm not sure what the loop does in this case. I don't think there will ever be a case where .clicked() is empty AND rects.nodes().pop() won't be empty. 
 
```javascript   first_cluster_idx = typeof first_cluster_idx == "undefined" ? Math.floor(Math.random() * 239) : first_cluster_idx ```

**Comment by ArtPoon** [comment]
This is progress, but search is still broken.
* reload page
* search for "Canada"
* submit search with enter, page switches to cluster with beads highlighted but no clusters in tree are selected
* pressing "Next" throws the following error:
```js
(index):279 Uncaught TypeError: Cannot read property 'id' of null
    at HTMLButtonElement.<anonymous> ((index):279)
    at HTMLButtonElement.dispatch (jquery.js:5429)
    at HTMLButtonElement.elemData.handle (jquery.js:5233)
```

**Comment by ewong347** [comment]
Looks like I might have broken the 'next' button with this fix.
I'm getting a Type error on current_cluster. Was this occurring before the fix?

```console
Uncaught TypeError: current_cluster is null
```

**Comment by ewong347** [comment]
Wait... I don't think this is a real fix, setting a random first cluster doesn't actually display a cluster that has the search term in it. Rollingback d326afc (done).  

Went back to the function to do a line-by-line stepforward using breakpoints. The problem is still with Line 62:70 as identified above. The filtering function (datum.searchtext.match(substr) !== null) is to blame here I think. I've tried the filtering function as a constant defined in ```select_beads_by_substring```, and additionally in the same way that it appears (inline) in the search by accession function.

Here's the comparison between search by accession and search by string:

Accession 
![Screen Shot 2020-11-16 at 9 47 38 PM](https://user-images.githubusercontent.com/44472547/99340858-d6bde600-2856-11eb-8a22-7abe4d71cac0.png)

String
![Screen Shot 2020-11-16 at 9 57 02 PM](https://user-images.githubusercontent.com/44472547/99340789-b1c97300-2856-11eb-9b92-d8213417ea40.png)
Here the vars ```first_cluster_idx``` and ```d.cluster_idx``` are both undefined. Firefox eventually ends up in a timeout loop because of undefined input (TypeError).


Can someone jump in here? Not sure how exactly the filtering function works

**Comment by ArtPoon** [comment]
what the heck is `datum`?

**Comment by ArtPoon** [comment]
afaik `filter` applies an anonymous "lambda" function to every item in an iterable object (*e.g.*, array) and returns a subset of every item for which the function evaluates `true`

**Comment by ewong347** [comment]
No clue what the point of using a datum was, I hadn't seen it used before, it's a [d3 data object](https://stackoverflow.com/questions/13728402/what-is-the-difference-d3-datum-vs-data#comment49437524_13730996). I didn't want to touch someone else's workflow in-case it [broke something](https://xkcd.com/1172/)

**Comment by ArtPoon** [comment]
Yeah I figured out as much re: d3, but it's not documented in the code and seems to be used at arbitrary scope throughout `search.js`.  I don't like it :-)

**Comment by ArtPoon** [comment]
Running through the following lines manually at commit 3e4af2fd114b95f1a0a77522a63c064d070b96b7:
https://github.com/PoonLab/covizu/blob/3e4af2fd114b95f1a0a77522a63c064d070b96b7/index.html#L276-L286

yields the following results:
<img width="667" alt="Screen Shot 2020-11-18 at 10 33 15 PM" src="https://user-images.githubusercontent.com/1109328/99617870-37335b80-29ee-11eb-8f3d-d9c4212f77fc.png">

**Comment by ArtPoon** [comment]
Note search seems to correctly jump to the correct bead plot, but none of the "beads" are selected - this may be related?

**Comment by ArtPoon** [comment]
Ok that last problem was because I was sending two Selectors to `select_beads_by_comparitors`, but the first Selector is used to trigger a refocus to the first matching cluster's beadplot.  Since the second Selector has already been called, it only contains beads for the default beadplot.  I've modified the code to separate `select_beads_by_comparitors` into separate functions.  Issue with `next` button remains.

**Comment by ArtPoon** [comment]
This code is part of the problem:
https://github.com/PoonLab/covizu/blob/3e4af2fd114b95f1a0a77522a63c064d070b96b7/js/drawtree.js#L291-L308

The problem is that `this` refers to a `rect` element, to which we have assigned an arbitrary string as `id`:
https://github.com/PoonLab/covizu/blob/3e4af2fd114b95f1a0a77522a63c064d070b96b7/js/drawtree.js#L281

The use of `this.id` implies that `start_idx` is an associative list (Object).  However, `start_idx` is initialized as an Array:
https://github.com/PoonLab/covizu/blob/3e4af2fd114b95f1a0a77522a63c064d070b96b7/js/search.js#L26-L35

Attempting to index into an Array with a string will return `undefined`.

**Comment by ArtPoon** [comment]
Fixed.  The problem was that I changed the DOM (muahahaha!).
This line:
`var rect = d3.selectAll('#svg-timetree > svg > g > rect')`
had to be changed to:
`var rect = d3.selectAll('#svg-timetree > svg > rect')`
