### ISSUE TITLE
Might be a bug

### ISSUE THREAD

**Issue by animesh-workplace** [PoonLab/covizu#278]
Take a look at the position of B.1.609 in the first image. My concern is that B.1.609 might be wrongly placed in that position as it has only two similar mutations compared to the rest of the lineages in that cluster while others have lot more mutations.

Could you help me out in understanding why it positioned so?

![image](https://user-images.githubusercontent.com/55780901/116095452-0d314400-a6c6-11eb-80ca-d87ebd045beb.png)
![mini](https://user-images.githubusercontent.com/55780901/116096038-8df04000-a6c6-11eb-8b6b-b77ae8c35a1e.png)

**Comment by ArtPoon** [comment]
Ha, I was just preparing to write an issue up on exactly the same thing.  
The tooltip does not list any synonymous substitutions — B.1.609 might share some in common with B.1.617, but I haven't checked.  
The underlying problem is that we rely on using a single genome sequence per PANGO lineage to reconstruct this tree.  We are currently taking the most recent sample that is available for each PANGO lineage, which has the benefit of mapping the tips of the tree to the most recent dates.  (It also gives us more variation to work with than if we take the earliest sample.)  Taking just one genome per lineage, however, means there were inevitably be some uncertainty in placement of lineages on the tree.

**Comment by ArtPoon** [comment]
We noticed some other issues with the time-scaled tree, so we're going to investigate using the earliest samples instead of most recent samples.

**Comment by animesh-workplace** [comment]
@ArtPoon Great work in creating such a nice visualization tool really helps a lot. 
I have a suggestion instead of using the earliest/most sample to generate the time-scaled tree why not use the [PangoLEARN decision tree rules](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/decision_tree_rules.txt) to generate the time-scaled tree which might eliminate the uncertainty in the placement of the tree. I know your approach has the added benefit of mapping the tips and getting more variation.

**Comment by ArtPoon** [comment]
A couple of reasons:
- we do not do Pangolin classifications ourselves (although we used to) - instead, we use the labels in the GISAID database
- the decision tree rules are encoded by a 40MB file that is constantly being updated - I would rather minimize the number of inputs

**Comment by animesh-workplace** [comment]
@ArtPoon Outbreak.info calls substitutions as lineage defining when it has reached to the 70% of the population in that lineage. They also use the same lineage classification provided by GISAID. May be you can look into that.

**Comment by ArtPoon** [comment]
@animesh-workplace - thanks for this info.  We arbitrarily go with 50%, but we don't declare these to be "lineage defining" mutations either.

**Comment by ArtPoon** [comment]
The original issue here is related to another issue, #245 that has also wandered.  Basically, we need to use earliest samples instead of most recent samples as lineage representative genomes for reconstructing the time-scaled tree.  Close both issues and create a new one that is on topic.
