### ISSUE TITLE
Add script to update problematic sites VCF and Pango lineages.csv

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#334]

**Comment by ArtPoon** [comment]
@GopiGugan determined that Pangolin updates git submodules rather than deleting and downloading dependencies

**Comment by GopiGugan** [comment]
Found that Pangolin actually appends a version number to their filename. In order to see if a file needs to be updated, they need to check the version number in the filename.

https://github.com/cov-lineages/pangolin/blob/e0ceede29c0e4c07ec63dd5799b87e628cac995f/pangolin/command.py#L513-L514

However, this would not work in our case. 

#### Potential Solution:

Add the two repositories as submodules:
- `git submodule add https://github.com/W-L/ProblematicSites_SARS-CoV2/`
- `git submodule add https://github.com/cov-lineages/pango-designation/`

Update submodules before running the pipeline:
- `git submodule foreach git pull origin master`

**Comment by ArtPoon** [comment]
Would need to change the paths for the respective files

**Comment by ArtPoon** [comment]
Can we try this out in a new branch?

**Comment by ArtPoon** [comment]
@GopiGugan investigating how to revise setup script to accommodate submodules

**Comment by ArtPoon** [comment]
@GopiGugan is working on building this functionality into the `batch.py` script in another branch
Note that `git` will become a package dependency with this new functionality.

**Comment by ArtPoon** [comment]
Pending test in branch `issue334`
