### ISSUE TITLE
Click to select vertical line in beadplot 

### ISSUE THREAD

**Issue by bonnielu** [PoonLab/covizu#342]

**Comment by bonnielu** [comment]
**Bugs/Edge cases that still need to be addressed:**
- Stroke-width of beads not visible after clicking vertical edge
- Edge selection working in conjunction with search/selectionH

**Comment by ArtPoon** [comment]
@ebrintn and @bonnielu to meet to discuss how to make a state diagram to track UX

**Comment by ebrintn** [comment]
Here are the sequence diagrams for the front end - I had to divide into two different diagrams because the free version of the program I was using would only let me have so many shapes. 

@bonnielu let me know if I am missing anything. 
![COVIZU Front end - 1](https://user-images.githubusercontent.com/37120899/134823941-4c406afd-59bb-47d4-807e-1dd322b2758d.png)
![COVIZU Front End - 2](https://user-images.githubusercontent.com/37120899/134823943-a88e7efd-6e80-4819-b4bd-d5dd1c780a41.png)

**Comment by ArtPoon** [comment]
This is a useful diagram - can we look into moving it out of this specific issue and into our dev documentation as a Mermaid diagram?

**Comment by ArtPoon** [comment]
Close upon testing dev branch in PR #354
