### ISSUE TITLE
Need visual feedback on selected objects (clusters, beads, etc)

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#53]
Presently we have feedback for mouseover events but not selection

**Comment by ArtPoon** [comment]
@RouxCil - Shall we draw a highlight ("halo") around a selected object by adding another shape in the SVG?
This gives us more options than if we are modifying the existing object using limited methods, *e.g.,* thicker border, slightly larger area.

**Comment by RouxCil** [comment]
@ArtPoon I was thinking of modifying the opacity of the entire plot such that the "clicked" object was the only fully opaque object. Thinking that this will extend well to the search function making the relevant objects "pop". We could also make subsets of the plot opaque depending on what is selected. My hesitation to adding more objects would be that the graph is already pretty busy and such object could "easily" be overlooked, but this can easily be fixed by the implementation.

**Comment by ArtPoon** [comment]
Ok, I am ok with the opacity approach, and I'd rather not have to deal with second layers for both timetree and cluster SVGs.  
Also, please see #64

**Comment by ArtPoon** [comment]
Look into directly annotating objects (beads, variants, etc.) with a `selected` attribute that is set to `true` or `false` to determine how that object is rendered in the SVG.

**Comment by ArtPoon** [comment]
Please provide feedback on current implementation of bead selection here!

**Comment by ArtPoon** [comment]
@RouxCil can we please temporarily switch this off in `dev` branch and do further development in a new branch?

**Comment by RouxCil** [comment]
@ArtPoon Done

**Comment by ArtPoon** [comment]
Thanks very much!

**Comment by RouxCil** [comment]
`issue53` branch has been merged with `dev`
