### ISSUE TITLE
Bar chart for continent distribution

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#67]
See #25

**Comment by ArtPoon** [comment]
* see how horizontal layout looks
* color bars using same continental palette (see #54)
* see if this gives us a way to address (#55) - barplot would need to be displayed at all times (even when nothing is selected)

**Comment by ArtPoon** [comment]
This plot needs to be smaller! 250px width limit

**Comment by ArtPoon** [comment]
Reformatted bar chart in `dev` branch - axis labels are messed up.

**Comment by kwade4** [comment]
I fixed the axis labels, rotated the region names to keep the font size consistent, and slightly increased the svg height from 150px to 200px.  Is there a height restriction for the graph?
![Screenshot from 2020-06-22 17-32-07](https://user-images.githubusercontent.com/48563808/85339012-49e24c80-b4b1-11ea-93d1-6b5bca8f5693.png)

**Comment by ArtPoon** [comment]
No height restriction for either graph (tree or beadplot) -  that's intentional
thanks

**Comment by ArtPoon** [comment]
Looks great! :clap:

**Comment by RouxCil** [comment]
Bar chart does not switch to the bead distribution when a bead is clicked, but stays at the cluster level.

**Comment by kwade4** [comment]
It appears to be working in `master`. I can look into why it doesn't work in the `dev` branch.

**Comment by kwade4** [comment]
I think this issue arises because the `div` that holds the bar chart is not set to empty before a new element is added. This causes the bead-level chart to appear underneath the cluster-level chart. 


Adding `.html("")` to the line 459 will set the `div` to empty. 
https://github.com/PoonLab/covizu/blob/d8cbd72597a489aa366fadb2107d537ffd13b6f7/js/beadplot.js#L458-L462
