### ISSUE TITLE
front-end -> dev masking beadplot and info column

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#84]
![Screenshot from 2020-06-16 14-46-09](https://user-images.githubusercontent.com/1109328/84815007-5b72b280-afe0-11ea-86fa-9d93e2bfd80b.png)
![Screenshot from 2020-06-16 14-47-02](https://user-images.githubusercontent.com/1109328/84815022-5e6da300-afe0-11ea-9496-e403163b650e.png)

**Comment by MomomomoLiu** [comment]
I think the sidebar masking the beadplot and info column because your testing window is a bit small. this is how it looks like in my computer.
![image](https://user-images.githubusercontent.com/56363357/84953284-3e61e080-b0c1-11ea-906f-a52d98ad2752.png)
for now, I set the sidebar at 25% area on the right.  the sidebar will mask other stuffs when the window gets smaller. Here are some thoughts:
1. i can move the info column to the sidebar;
2. set the sidebar at 10% area on the right. (long info will display in several rows) 
![image](https://user-images.githubusercontent.com/56363357/84954135-d613fe80-b0c2-11ea-9a54-268c1ea29d41.png)

**Comment by ArtPoon** [comment]
Please incorporate the info column into the sidebar- thanks!
